commit XiangThree

diff --git a/tossug-arena b/tossug-arena
--- a/tossug-arena
+++ b/tossug-arena
@@ -3,6 +3,7 @@
 ARENA_ROUND=$1 # name of round file
 ARENA_PLAYER1=$2 # name of player1
 ARENA_PLAYER2=$3 # name of player2
+ARENA_PLAYER3=$4 # name of player3
 ARENA_GAME="" # game type from round file
 ARENA_UI="" # game ui from round file
 ARENA_THEME="" # ui theme from round file
@@ -12,7 +13,7 @@ RANDOM=`date +%s` # set random seed
 if [ $# -eq 0 ] ; then
   echo "TOSSUG Arena: Gamelets Arena for AI Players"
   echo "Usage:"
-  echo -e "\ttossug-arena ROUND [ PLAYER1 [ PLAYER2 ]]"
+  echo -e "\ttossug-arena ROUND [ PLAYER1 [ PLAYER2 [ PLAYER3 ]]]"
   echo
   echo "available ROUNDs:"
   cd "$DATADIR/rounds"
@@ -52,5 +53,11 @@ elif ! [ -x "$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER2/main" ] ; then
   echo "player path: $DATADIR/players/$ARENA_GAME/$ARENA_PLAYER2/main not found."
   exit 1
 fi
+if [ -z "$ARENA_PLAYER3" -o "${ARENA_PLAYER3,,}" = human ] ; then
+  ARENA_PLAYER3=Human
+elif ! [ -x "$DATADIR/players/$ARENA_GAME/$ARENA_PLAYER3/main" ] ; then
+  echo "player path: $DATADIR/players/$ARENA_GAME/$ARENA_PLAYER3/main not found."
+  exit 1
+fi
 
-exec "$DATADIR/uis/$ARENA_GAME/$ARENA_UI/main" "$ARENA_THEME" "$ARENA_PLAYER1" "$ARENA_PLAYER2"
+exec "$DATADIR/uis/$ARENA_GAME/$ARENA_UI/main" "$ARENA_THEME" "$ARENA_PLAYER1" "$ARENA_PLAYER2" "$ARENA_PLAYER3"
